### ISSUE TITLE
decoratorとFlask

### ISSUE THREAD

**Issue by Koyama-Tatsuya** [ksaki/SNS_studygroup#11]
gplus_search_web_gui.pyについてですが、コードはちゃんと回るのですが、いまいち意味が分かりません。

defで定義されている式の意味や、それによって出てくる結果などはわかるのですが、decoratorの説明など、良く分からない。

例えば、index()やsearch()を定義しているわけですが、何でapp.runだけでこれらの処理が行われているのか分かりません。

Flaskの話は、この本の主題ではないのでどうしても理解する必要があるわけではなさそうですが、もし分かる人がいたら教えてほしいです。

**Comment by dinglid** [comment]
FlaskはWeb サーバーとして理解すれば、まずそのサーバーというapp をapp.runで起動する、つまり:
if __name__ == '__main__':
     app.run(debug=True)

そして、サーバーが起動し動いています。
ここで誰かが
   http://127.0.0.1:5000/ 
にアクセスすれば、まずindex pageを表すのはweb site のルールで、ここでindexが何かを定義するのはこれ:
 @app.route('/') の中(‘/‘) -> 何もついていないのでdef indexでindex pageを定義する。http://127.0.0.1:5000/にアクセスする時表す。下のsearch page なら(‘search’)-> def searchで search pageを定義する。


ここで、app.route()、というのはdecoratorであって、このindexが何か、searchが何かをpythonで定義することによってflaskサーバー(library)のfunctionに情報を与える。そのため我々は具体的なwebページのコードを一々コーティングしなくて済む。apiとして理解すればいいかな。

というのは私の理解です。

**Comment by Koyama-Tatsuya** [comment]
なるほど。イメージとしてはすごく良く理解できました。

ということは、indexとかsearchっていうのは、どんな名前でもいいわけではないということですよね。これは関数として理解するべきなんでしょうか。「websiteのルール」とか、「webページのコード」というのは、htmlコードのことではないですよね？ウェブブラウザのAPIというような感じなのかな？

**Comment by dinglid** [comment]
ごめん、回答が雑すぎてもう一回します：
先ほどuploadしたgplus_search_web_gui_another_example.pyを見れば多分わかりやすいかな。。。
本のcodeでの流れは：
app.runでサーバー起動ー＞ユーザーが127.0.0.1:5000/にアクセス（もしdomainがあれば、たとえばwww.SNSstudygroup.comを自分のパソコンの127.0.0.1:5000/に反射させれば、www.SNSstudygroup.comを入力すれば同じ効果がある）
ー＞
@app.route('/')
def index():
の定義で127.0.0.1:5000/で実行するのはindexという関数を実行。なぜindexという名前なのかというと、これはweb designの約束（厳格的にはルールではないと思う）であるから、website(例えばhttps://www.oracle.com/)を訪問する際に最初にindex.html(https://www.oracle.com/index.html)に導く。でもそうではないwebsiteもいっぱいある。例えばgoogle.comにアクセスすればgoogle.com/index.htmlとなってない。ただ、名前にはかかわらず、ここで実際にindexとしての関数が実行されているのは間違いない。そのため@app.route('/')を他の名前の関数で定義しても構わないが、約束的にはdef index():となる。
ー＞index()が実行され、ここでただsearch_form.htmlというweb pageを機能的にindex pageとして表す
ー＞search_form.htmlを見ればわかるように、<form action="/search"　というactionがあって、ここでユーザーがsearchボタンを押せばこのactionが実行され、127.0.0.1:5000/searchに導く。
ー＞python fileの@app.route('/search', methods=['POST'])　def search():　という定義があって、indexと同じように127.0.0.1:5000/searchにアクセス（ここで直接web link入力することができず、searchボタンを通じてアクセスしかない）すれば　searchという関数を実行する。

という流れです。
一方、gplus_search_web_gui_another_example.pyの流れとしては：
app.runでサーバー起動ー＞ユーザーが127.0.0.1:5000/を入力すれば404not foundのerrorが出る。なぜだというと、ここで127.0.0.1:5000のあと/しかついていないリンクが定義されていない。定義されているのは127.0.0.1:5000/indexなので、127.0.0.1:5000/index　で入力しかないという。
ー＞
@app.route('/index')
def indexss():
によれば、127.0.0.1:5000/indexにアクセスすればindexss（もともとはindex）という関数が実行される。ここで名前（indexかindexssか）ということが関係なく、pythonで前処理、例えばmessage = 'ここでsearch queryを入力してください!'という情報をweb pageに与えることができるわけです。
ー＞
次に同じくsearchボタンを押せば、ここでのactionを<form action="/search2" method="post">として定義すれば、@app.route('/search2', methods=['POST'])と対応する。ここでの[/search2]は、前の[/]と[/search]、[/index]と同じように対応している。@app.routeというdecoratorはflaskに、もしこのweb linkにアクセスすれば、どんな関数を実行すればいいのか、を教えることになる。このようなsearchやindexの名前は何でもよいだが、一応約束的には[/]あるいは[/index]ー＞index機能のもつ関数と対応する、[/search]ー＞検索機能のもつ関数と対応する、ということになる。
ー＞
127.0.0.1:5000/search2にアクセスすれば（直接はできず、searchボタンをつうじて）、@app.route('/search2', methods=['POST'])
def search2222():
の定義でsearch2222という関数を実行する。

要するに、/xxxxx的なものはweb linkとしてユーザーのbrowserで表示されているため、約束や簡潔にする必要がある（search2というのはよくない）。web linkと対応する関数　index,indexss,search,search2222の名前は好きにすればいい、プログラマー同士しか見られないからです。
APIとして理解すればいいという話は、127.0.0.1:5000/searchというのはAPIのlinkとよく似ているから。ユーザーが127.0.0.1:5000/xxxxにアクセスして、その/xxxxと対応する関数が実行されるということである。つまり、127.0.0.1:5000/xxxxの/xxxxは関数ではなく、app.routeの定義で/xxxx対応しているxxxx222()が実行されるということです。
