### ISSUE TITLE
parse.add_argument('--no-idf'について

### ISSUE THREAD

**Issue by Koyama-Tatsuya** [ksaki/SNS_studygroup#4]
parser.add_argument('--no-idf', dest='use_idf', default=True, action='store_false')
	#switch off the use of idf(inverse document frequency) and use only tf (term frequency)
	#dest?? action??

葛島さんのこの部分ですが、https://docs.python.jp/3/library/argparse.htmlを参照すると、

destについては、parserが格納する値の属性名を指定しているのだと思います。
他のものについては指定がないので、入力の名前がそのまま属性名になります。
args.kとか、args.min-dfとかです。

しかし、ここではあえて別の名前を指定しているので、
args.no-idfとはならず、args.use_idfとなります。
何でわざわざこうしているのかは謎。

action=store_falseはちょっと難しそうです。自信はあまりないのですが、

`import sys
from argparse import ArgumentParser

def get_parser():
    parser = ArgumentParser("test")
    parser.add_argument("--test", action = "store_false", default = True)
    return parser

parser = get_parser()
args = parser.parse_args()
print(args)`

このコード(testparse.py)で試したところ、
`python testparse.py`とすると、Namespace(test=True)
`python testparse.py --test`とすると、Namespace(test=False)

となっていました。
おそらく、argumentを指定することで、このアクションが喚起されるということでしょう。
何もしなければtestにはdefaultが入っていますが、argumentに値を入れなくても、その名前をいれただけで、特定の操作をするような場合に使われるようです。この場合は、testにFalseを格納するわけですが。

実際、twitter_cluster_users.pyで、idfをオフにしたい場合、
--no-idf Trueとか、--no-idf Falseとかにしてもエラーになり、
--no-idf
とargumentの項目名を打つだけ(flagを立てるだけ？)でidfは切られます。
Rとかだとあまりないargumentの使い方ですが、no-idfと打てば、idfがオフになるというのは理に適ったデザインでしょう。

**Comment by ksaki** [comment]
ありがとうございます！
actionを指定したら、defaultは自動で決まるみたいですね。default=Trueを消しても同じ結果がでました。
二重に書く必要はなさそうですが、わかりやすいからですかね。

**Comment by Koyama-Tatsuya** [comment]
そうじゃないですかね。

でもdefault=Trueを消しても、actionがstore_faulseだから、defaultでTrueを格納するというのは、不思議ですね。普通、NullとかNoneとかじゃないんですかね。
そういうものと言われたらそれまでですが。
