### ISSUE TITLE
DiGraphの.degree_iter(

### ISSUE THREAD

**Issue by Koyama-Tatsuya** [ksaki/SNS_studygroup#5]
twitter_conversation.pyで以下のエラーが出ます。
ちなみに、ノードとかエッジの数はちゃんと出てます。そのあとに以下のメッセージ。
フルコードは一番下に乗せときます。

Traceback (most recent call last):
  File "twitter_conversation.py", line 34, in <module>
    sorted_replied = sorted(graph.degree_iter(),
AttributeError: 'DiGraph' object has no attribute 'degree_iter'

https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.DiGraph.degree_iter.html
こことか見る感じだと、DiGraphのattributeとして、確かにdegree_iterは存在するように思えるのですが、皆さん同じエラーは出ていませんか？

`import sys
import json
from operator import itemgetter
import networkx as nx

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)
    fname = sys.argv[1]
    with open(fname) as f:
        graph = nx.DiGraph()
        for line in f:
            try:
                tweet = json.loads(line)
            except:
                continue
            if "id" in tweet:
                graph.add_node(tweet["id"],
                              tweet=tweet["text"],
                              author=tweet["user"]["screen_name"],
                              created_at=tweet["created_at"])
                if tweet["in_reply_to_status_id"]:
                    reply_to = tweet["in_reply_to_status_id"]
                    if reply_to in graph and tweet["user"]["screen_name"] != graph.node[reply_to]["author"]:
                        graph.add_edge(tweet["in_reply_to_status_id"],
                                       tweet["id"])
        print(nx.info(graph))
        sorted_replied = sorted(graph.degree_iter(),
                               key=itemgetter(1),
                               reverse=True)
        most_replied_id, replies = sorted_replied[0]
        print("Most replied tweet ({} replies):".format(replies))
        print(graph.node[most_replied_id])
        
        print("Longest discussion:")
        longest_path = nx.dag_longest_path(graph)
        for tweet_id in longest_path:
            node = graph.node(tweet_id)
            print("{} (by {} at {})".format(node["tweet"],
                                           node["author"],
                                           node["created_at"]))`

**Comment by ksaki** [comment]
エラーは出なかったですが、longest discussionのあと何もprintされなかったです。
おそらくedge数が0、つまり会話がなかったので。。。
時間があれば会話があるデータをとってきてやってみます
