### ISSUE TITLE
Facebook API user access token expires!

### ISSUE THREAD

**Issue by ksaki** [ksaki/SNS_studygroup#7]
どうやら教科書に乗っているuser access tokenは数時間で期限切れしてしまうようで、どうにかすると期限を60日程度に延長できるみたいなんですが、やりかたがいまいち分からず困っています。

やりかたはここに書いてあるのですが、黒背景の部分のテキストをどこに入力すればよいのかわかりません。
https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/#generate-long-lived-token
出来た人いますか？？

**Comment by ksaki** [comment]
言ったそばからすみませんが、なぜかできました。
Graph API ExplorerでAccess Tokenの左端のiマークをクリック -> Open Access Token Toolをクリック -> 下方にあるExtend Access Tokenをクリック -> 自分のFBパスワードを入力 -> 完了　でした。

**Comment by Koyama-Tatsuya** [comment]
ありがとうございます。教科書だと2時間しか持たないっていうことが書いてあるだけですね。
同様の手続きで僕もできたので、これをやっておいた方が便利ですね。
