### ISSUE TITLE
facebook.GraphAPIError: (#10)

### ISSUE THREAD

**Issue by ksaki** [ksaki/SNS_studygroup#8]
p.145以降の、Facebook Pageから色々な情報をとるコードを動かすには、
どうやら作成したアプリがfacebookにreviewされることが必要みたいです。
以下のようなエラーが出ました。

facebook.GraphAPIError: (#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.

この問題を回避できた方はいますか？アプリの作成者のみがユーザーの場合はApp reviewしなくてよいと書かれていたのですが、App reviewに出しましたか？

**Comment by Koyama-Tatsuya** [comment]
同じ箇所で同じエラーでした。

https://stackoverflow.com/questions/50151567/read-public-posts-from-own-facebook-pages-timeline-pages-api-requires-revie

この人の感じだと、2018年3月から8月の措置として、レヴューを要求される範囲が拡大しているということなのでしょうか。そうだとすれば、回避することはできないことになりますね。
他に何かわかる人がいたらお願いします。
