### ISSUE TITLE
p123のfolium.GeoJsonについて

### ISSUE THREAD

**Issue by Koyama-Tatsuya** [ksaki/SNS_studygroup#9]
facebookがうまく動かないので、twitterの続きです。

地図をfoliumを使って書くところがありますが、そのままやるとエラーが出ました。

\Users\ebenh\Documents\MSMMwP>python twitter_map_basic.py --geojson "wttc_geo.jsonl" --map "wttc_geo.html"
Traceback (most recent call last):
  File "twitter_map_basic.py", line 26, in <module>
    make_map(args.geojson, args.map)
  File "twitter_map_basic.py", line 17, in make_map
    name='geojson')
  File "C:\Users\ebenh\Anaconda3\lib\site-packages\folium\features.py", line 495, in __init__
    raise ValueError('Unhandled object {!r}.'.format(data))
ValueError: Unhandled object <_io.TextIOWrapper name='wttc_geo.jsonl' mode='r' encoding='cp932'>.

どうやら、geojsonのファイルのエンコーディングに問題があったようです。
https://gis.stackexchange.com/questions/257802/understanding-valueerror-from-folium
ここなんかを参考にして、

geojson_layer = folium.GeoJson(open(geojson_file),
                                                     name="geojson")

という箇所を、

geojson_layer = folium.GeoJson(open(geojson_file, encoding = "cp932").read(),
                                                     name="geojson")

としたところ、きちんと回りました。

以下が出力です。
しかし、15万のツイートを使っているのですが、geotagがついているのは70ツイート程度でした。少なすぎる気がするのですが。。。

あとは、これは卓球世界選手権についてのツイートを集めていて、確か時間帯的には東南アジアの国が割合多く試合していた時間だったので、東南アジアからのツイートが非常に多いです。意外と東南アジアの人も卓球に関心があるのだな～と感じました。

[wttc_map.pdf](https://github.com/ksaki/SNS_studygroup/files/2000420/wttc_map.pdf)

**Comment by ksaki** [comment]
encodingの変数は入れなくても回りましたが、.read()は必要でした。
そもそもどのencodingにすれば良いかってどこみれば書いてあるんですか...？

geotagは私も異様に少なかったです。2/47でした。
まあでもtwitterを眺めてる感じでも、geotagがついてるツイートって割りと少ないような気がします。。
